config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  # Defines the root path route ("/")
  # root "articles#index"
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new',  as: :new_task
  get '/tasks/:id', to: 'tasks#show', as: :task
  post '/tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'

  get 'tasks/:id/mark_as_done', to: 'tasks#mark_as_done', as: :mark_as_done

  # resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path(@task)
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def mark_as_done
    @task = Task.find(params[:id])
    @task.update(completed: true)
    redirect_to tasks_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@task), status: :see_other
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group w-50">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group w-50">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>

<%
=begin %>

<%= form_with model: @task do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    </div>
  <% end %>
  <%= f.submit class: 'btn btn-primary mt-3' %>
<% end %>

<%
=end %>

app/views/tasks/destroy.html.erb
<h1> Delete task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.number_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<div class="container mt-5">
  <h1>Edit task</h1>

  <%= render "form", task: @task %>

  <hr class="w-50">
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

<%
=begin %>

<h1>Edit task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

<%
=end %>

app/views/tasks/index.html.erb
<div class="container mt-5">
  <h1 class="mb-3">My tasks</h1>

  <ul id="tasks">
    <% @tasks.each do |task| %>
      <li class="m-2">
        <% if task.completed? %>
          <i class="fa-regular fa-square-check"></i>
        <% else %>
          <i class="fa-regular fa-square"></i>
        <% end %>
        <%= link_to task.title, task_path(task.id) %>
        <%= link_to task_path(task.id), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      </li>
    <% end %>
  </ul>

  <hr class="w-50">

  <%= link_to new_task_path do %>
    <i class="fa-solid fa-plus"></i> Add a new task
  <% end %>
</div>


<%
=begin %>

<h1 class="mt-3">My Tasks</h1>
<div class="m-3"> ➕<%= link_to 'Add a task', new_task_path , class: "btn btn-primary"%> </div>

<ul class="m-3 list-group">
  <% @tasks.each do |task| %>
    <li class="w-25 p-3 list-group-item text-center"><%= link_to task.title, task_path(task)%><div class: "text-right"><%=task.completed == true ? "✅" : "⬜️"%></div></li>
  <% end %>
</ul>

<%
=end %>

app/views/tasks/new.html.erb
<div class="container mt-5">
  <h1>New task</h1>

  <%= render "form", task: @task %>

  <hr class="w-50">
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
</div>

<%#
<h1>Create a task</h1>


<%= form_for(@task) do |f| %>
  <%# <%= f.label :title %>
  <%# <%= f.text_field :title %>
  <%# <%= f.label :details %>
  <%# <%= f.text_field :details %>
  <%# <%= f.label :completed %>
  <%# <%= f.check_box :completed %>
  <%# <%= f.submit %>
<%# <% end %>

app/views/tasks/show.html.erb
<div class="container mt-5">
  <div class="d-flex justify-content-between align-items-center mb-4">
    <h1><%= @task.title %></h1>
    <%= link_to edit_task_path(@task.id), class: 'btn btn-light btn-sm border' do %>
      <i class="fa fa-pencil"></i> Edit this task
    <% end %>
  </div>


  <p class="well"><%= @task.details %></p>

  <% if @task.completed %>
    <i class="fa fa-check-square-o"></i> This task is completed
  <% else %>
    <i class="fa fa-square-o"></i> This task is not completed yet
  <% end %>

  <hr class="w-50">
  <%= link_to tasks_path do %>
    <i class="fa-solid fa-arrow-rotate-left"></i> Back to list
  <% end %>
  <%= link_to mark_as_done_path(@task.id), class: 'btn btn-light btn-sm border ms-3' do %>
    <i class="fa fa-check"></i> Mark as completed
  <% end %>

</div>

<%
=begin %>

<h2 class="m-3"><%= @task.title %></h2>
<p>- <%= @task.details %></p>
<p><%= @task.completed %></p>

<div><%= link_to 'Edit task', edit_task_path, class: "btn btn-success"%> | <%= link_to "Delete", task_path(@task), class: "btn btn-success",
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></div>

<%= link_to 'Back Home', tasks_path, class: "m-3 btn btn-primary"%>

<%
=end %>